name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Build the Docker image
      run: docker buildx build --target minimal-plus . --file Dockerfile --tag pwabuilder.azurecr.io/pwa-android-build-box:preview
      
    - name: Login
      run: docker login pwabuilder.azurecr.io -u pwabuilder --password ${{secrets.azure}}
      
    - name: Push
      run: docker push pwabuilder.azurecr.io/pwa-android-build-box:preview
     
    
